export enum TokenType {
  INT = 'INT',
  FLOAT = 'FLOAT',
  PI = 'PI',
  KET_LITERAL = 'KET_LITERAL',
  IDENT = 'IDENT',
  QUBIT = 'QUBIT',
  BIT = 'BIT',
  ANGLE = 'ANGLE',
  COMPLEX = 'COMPLEX',
  GATE = 'GATE',
  CIRCUIT = 'CIRCUIT',
  LET = 'LET',
  MEASURE = 'MEASURE',
  RUN = 'RUN',
  ON = 'ON',
  IBM = 'IBM',
  REPEAT = 'REPEAT',
  IF = 'IF',
  MATCHES = 'MATCHES',
  DIFFUSE = 'DIFFUSE',
  PHASE_ORACLE = 'PHASE_ORACLE',
  QFT = 'QFT',
  GROVER_DIFFUSE = 'GROVER_DIFFUSE',
  GATE_H = 'GATE_H',
  GATE_X = 'GATE_X',
  GATE_Y = 'GATE_Y',
  GATE_Z = 'GATE_Z',
  GATE_S = 'GATE_S',
  GATE_T = 'GATE_T',
  GATE_RX = 'GATE_RX',
  GATE_RY = 'GATE_RY',
  GATE_RZ = 'GATE_RZ',
  GATE_CNOT = 'GATE_CNOT',
  GATE_CZ = 'GATE_CZ',
  GATE_SWAP = 'GATE_SWAP',
  GATE_TOFFOLI = 'GATE_TOFFOLI',
  SQRT = 'SQRT',
  FLOOR = 'FLOOR',
  CEIL = 'CEIL',
  PLUS = 'PLUS',
  MINUS = 'MINUS',
  STAR = 'STAR',
  SLASH = 'SLASH',
  EQ_EQ = 'EQ_EQ',
  EQUALS = 'EQUALS',
  LPAREN = 'LPAREN',
  RPAREN = 'RPAREN',
  LBRACKET = 'LBRACKET',
  RBRACKET = 'RBRACKET',
  LBRACE = 'LBRACE',
  RBRACE = 'RBRACE',
  COMMA = 'COMMA',
  COLON = 'COLON',
  NEWLINE = 'NEWLINE',
  EOF = 'EOF'
}

export interface Token {
  type: TokenType;
  value: string;
  line: number;
  column: number;
}

export const KEYWORDS: ReadonlyMap<string, TokenType> = new Map([
  ['qubit', TokenType.QUBIT],
  ['bit', TokenType.BIT],
  ['angle', TokenType.ANGLE],
  ['complex', TokenType.COMPLEX],
  ['gate', TokenType.GATE],
  ['circuit', TokenType.CIRCUIT],
  ['let', TokenType.LET],
  ['measure', TokenType.MEASURE],
  ['run', TokenType.RUN],
  ['on', TokenType.ON],
  ['ibm', TokenType.IBM],
  ['repeat', TokenType.REPEAT],
  ['if', TokenType.IF],
  ['matches', TokenType.MATCHES],
  ['diffuse', TokenType.DIFFUSE],
  ['phase_oracle', TokenType.PHASE_ORACLE],
  ['qft', TokenType.QFT],
  ['grover_diffuse', TokenType.GROVER_DIFFUSE],
  ['H', TokenType.GATE_H],
  ['X', TokenType.GATE_X],
  ['Y', TokenType.GATE_Y],
  ['Z', TokenType.GATE_Z],
  ['S', TokenType.GATE_S],
  ['T', TokenType.GATE_T],
  ['Rx', TokenType.GATE_RX],
  ['Ry', TokenType.GATE_RY],
  ['Rz', TokenType.GATE_RZ],
  ['CNOT', TokenType.GATE_CNOT],
  ['CZ', TokenType.GATE_CZ],
  ['SWAP', TokenType.GATE_SWAP],
  ['Toffoli', TokenType.GATE_TOFFOLI],
  ['sqrt', TokenType.SQRT],
  ['floor', TokenType.FLOOR],
  ['ceil', TokenType.CEIL]
]);

export const RESERVED_KEYWORDS = new Set(KEYWORDS.keys());
